export const DIMENSIONS = {
  OBJECTMAP_WIDTH: 280,
  BOARD_WIDTH: 800,
  BOARD_HEIGHT: 600,
  POINT_RADIUS_NORMAL: 4,
  POINT_RADIUS_SELECTED: 6,
  POINT_RADIUS_FIRST: 8,
  POINT_STROKE_WIDTH: 2,
  STROKE_WIDTH_NORMAL: 1,
  STROKE_WIDTH_HOVERED: 2,
  STROKE_WIDTH_SELECTED: 3,
  LINE_OVERLAY_WIDTH: 4,
};